import { useEffect, useState } from 'react'
import jsPDF from 'jspdf'

interface JobSummary {
  job_id: string
  start_time: string
  end_time: string
  elapsed_time: number
  status: string
  total_records: number
  output_file: string
  format: string
  errors: string[]
  output_destination?: 'local' | 'ftp' | 'sftp'
  ftp_config?: {
    host: string
    port: number
    user: string
    directory: string
    use_tls: boolean
    passive_mode: boolean
  }
}

interface ProgressModalProps {
  isOpen: boolean
  progress: number
  status: string
  summary?: JobSummary
  onClose: () => void
}

function formatTimestamp(timestamp: string | null) {
  return timestamp ? new Date(timestamp).toLocaleString() : 'N/A'
}

function generatePDF(summary: JobSummary) {
  const doc = new jsPDF()
  const pageWidth = doc.internal.pageSize.width
  
  // Add company logo/header
  doc.setFillColor(41, 98, 255) // Primary color
  doc.rect(0, 0, pageWidth, 40, 'F')
  
  // Title
  doc.setFont('helvetica', 'bold')
  doc.setTextColor(255, 255, 255)
  doc.setFontSize(24)
  doc.text('Export Summary', 20, 25)
  
  // Content
  doc.setTextColor(33, 33, 33)
  doc.setFontSize(12)
  doc.setFont('helvetica', 'normal')
  
  // Add timestamp in the corner
  doc.setFontSize(10)
  doc.setTextColor(128, 128, 128)
  doc.text(`Generated: ${new Date().toLocaleString()}`, pageWidth - 65, 10)
  
  // Main content
  const y = 60 // Starting y position after header
  const lineHeight = 7
  
  doc.setFont('helvetica', 'bold')
  doc.setFontSize(14)
  doc.setTextColor(41, 98, 255)
  doc.text('Export Details', 20, y)
  
  doc.setFont('helvetica', 'normal')
  doc.setFontSize(12)
  doc.setTextColor(33, 33, 33)
  
  // Details grid with null handling
  const details = [
    { label: 'Status', value: summary.status || 'N/A' },
    { label: 'Created', value: formatTimestamp(summary.start_time) },
    { label: 'Total Records', value: summary.total_records?.toLocaleString() || 'N/A' },
    { label: 'Output File', value: summary.output_file || 'Files downloaded successfully' },
    { label: 'Format', value: summary.format === 'files' ? 'FILES' : summary.format?.toUpperCase() || 'N/A' },
    { label: 'Duration', value: summary.elapsed_time ? `${summary.elapsed_time.toFixed(2)} seconds` : 'Processing...' },
    ...(summary.output_destination ? [{ label: 'Destination', value: summary.output_destination.toUpperCase() }] : [])
  ]
  
  // Add FTP details if present
  if (summary.output_destination === 'ftp' && summary.ftp_config) {
    details.push(
      { label: 'FTP Host', value: summary.ftp_config.host },
      { label: 'FTP Port', value: summary.ftp_config.port.toString() },
      { label: 'FTP User', value: summary.ftp_config.user },
      { label: 'FTP Directory', value: summary.ftp_config.directory },
      { label: 'TLS Enabled', value: summary.ftp_config.use_tls ? 'Yes' : 'No' },
      { label: 'Passive Mode', value: summary.ftp_config.passive_mode ? 'Yes' : 'No' }
    )
  }
  
  details.forEach((detail, i) => {
    const yPos = y + 20 + (i * lineHeight)
    doc.setFont('helvetica', 'bold')
    doc.text(`${detail.label}:`, 20, yPos)
    doc.setFont('helvetica', 'normal')
    doc.text(detail.value, 80, yPos)
  })
  
  // Add errors section if any
  if (summary.errors.length > 0) {
    const errorY = y + 20 + (details.length * lineHeight) + 15
    
    doc.setFont('helvetica', 'bold')
    doc.setFontSize(14)
    doc.setTextColor(220, 38, 38)
    doc.text('Errors', 20, errorY)
    
    doc.setFont('helvetica', 'normal')
    doc.setFontSize(12)
    summary.errors.forEach((error, i) => {
      doc.text(`• ${error}`, 25, errorY + 10 + (i * 7))
    })
  }
  
  // Add footer
  const footerY = doc.internal.pageSize.height - 20
  doc.setFontSize(10)
  doc.setTextColor(128, 128, 128)
  doc.text('Generated by Data Export Tool', 20, footerY)
  doc.text(`Job ID: ${summary.job_id}`, pageWidth - 60, footerY)
  
  doc.save(`export-summary-${summary.job_id}.pdf`)
}

export function ProgressModal({ isOpen, progress, status, summary, onClose }: ProgressModalProps) {
  const [dots, setDots] = useState('.')

  useEffect(() => {
    if (!isOpen) return

    const interval = setInterval(() => {
      setDots(prev => prev.length >= 3 ? '.' : prev + '.')
    }, 500)

    return () => clearInterval(interval)
  }, [isOpen])

  if (!isOpen) return null

  return (
    <div className="modal-overlay">
      <div className="modal-content">
        {!summary ? (
          // Show progress during export
          <>
            <div className="progress-container">
              <div className="progress-bar">
                <div 
                  className="progress-fill" 
                  style={{ width: `${progress}%` }}
                />
              </div>
              <div className="progress-text">
                {progress}%
              </div>
            </div>
            <div className="status-text">
              {status}{dots}
            </div>
          </>
        ) : (
          // Show summary after completion
          <div className="summary-container">
            <div className="summary-header">
              <h3>Export Summary</h3>
              <button 
                className="pdf-btn"
                onClick={() => generatePDF(summary)}
                title="Download PDF"
              >
                <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2">
                  <path d="M14 2H6a2 2 0 0 0-2 2v16a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V8z"/>
                  <polyline points="14 2 14 8 20 8"/>
                  <line x1="12" y1="18" x2="12" y2="12"/>
                  <line x1="9" y1="15" x2="15" y2="15"/>
                </svg>
              </button>
            </div>
            
            <div className="summary-grid">
              <div className="summary-item">
                <label>Status:</label>
                <span>{summary.status || 'N/A'}</span>
              </div>
              <div className="summary-item">
                <label>Created:</label>
                <span>{formatTimestamp(summary.start_time)}</span>
              </div>
              <div className="summary-item">
                <label>Total Records:</label>
                <span>{summary.total_records?.toLocaleString() || 'N/A'}</span>
              </div>
              <div className="summary-item">
                <label>Output File:</label>
                <span>{summary.output_file || 'Files downloaded successfully'}</span>
              </div>
              <div className="summary-item">
                <label>Format:</label>
                <span>{summary.format === 'files' ? 'FILES' : summary.format?.toUpperCase() || 'N/A'}</span>
              </div>
              <div className="summary-item">
                <label>Duration:</label>
                <span>{summary.elapsed_time ? `${summary.elapsed_time.toFixed(2)} seconds` : 'Processing...'}</span>
              </div>
              {summary.output_destination && (
                <div className="summary-item">
                  <label>Destination:</label>
                  <span>{summary.output_destination.toUpperCase()}</span>
                </div>
              )}
              {summary.output_destination === 'ftp' && summary.ftp_config && (
                <div className="ftp-details">
                  <h4>FTP Configuration</h4>
                  <div className="summary-item">
                    <label>Host:</label>
                    <span>{summary.ftp_config.host}</span>
                  </div>
                  <div className="summary-item">
                    <label>Port:</label>
                    <span>{summary.ftp_config.port}</span>
                  </div>
                  <div className="summary-item">
                    <label>User:</label>
                    <span>{summary.ftp_config.user}</span>
                  </div>
                  <div className="summary-item">
                    <label>Directory:</label>
                    <span>{summary.ftp_config.directory}</span>
                  </div>
                  <div className="summary-item">
                    <label>TLS Enabled:</label>
                    <span>{summary.ftp_config.use_tls ? 'Yes' : 'No'}</span>
                  </div>
                  <div className="summary-item">
                    <label>Passive Mode:</label>
                    <span>{summary.ftp_config.passive_mode ? 'Yes' : 'No'}</span>
                  </div>
                </div>
              )}
              {summary.errors?.length > 0 && (
                <div className="summary-item errors">
                  <label>Errors:</label>
                  <ul>
                    {summary.errors.map((error, i) => (
                      <li key={i}>{error}</li>
                    ))}
                  </ul>
                </div>
              )}
            </div>

            <button 
              className="close-btn"
              onClick={onClose}
            >
              Close
            </button>
          </div>
        )}
      </div>
    </div>
  )
} 